spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/news
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.40.134
      port: 6379
      password: 123321

mybatis:
  configuration:
    map-underscore-to-camel-case: true
